# Generated by Django 6.0.5 on 2026-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(choices=[('production', 'Production'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('procurement', 'Procurement'), ('hr', 'HR'), ('it', 'IT')], default='production', max_length=50),
        ),
    ]
