# Generated by Django 6.0.5 on 2026-05-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('procurement', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='production.finishedproduct'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='procurement.rawmaterial'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='production.finishedproduct'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.rawmaterial'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', True), ('raw_material__isnull', False)), models.Q(('finished_product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='stockmovement_exactly_one_item_type'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', True), ('raw_material__isnull', False)), models.Q(('finished_product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='stocklot_exactly_one_item_type'),
        ),
    ]
