# Generated by Django 6.0.5 on 2026-05-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.salesorderline'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_schedules', to='production.machine'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='production.productionorder'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterialline',
            unique_together={('bill_of_material', 'raw_material')},
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('product', 'version')},
        ),
    ]
