# Generated by Django 6.0.5 on 2026-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='product_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=32),
        ),
    ]
